ptmt/react-native-macos

React/Base/RCTUtils.m

Previously, backing scale factor was hardcoded to 1, which caused `<Image />` displayed wrong on Retina monitors.
Also I remove `dispatch_once` so RND could adapt to dynamic backing scale factor changes. Unlike iOS devices, dynamic backing scale factor changes are possible. (For example, user with dual displays might drag a window from a Retina display to another non-Retina display.) With profiling, I found that removing `dispatch_once` won't cause noticeable performance issue, unless you have hundreds of  `<Image />` to display at the same time.

Correct screen backing scale factor.

---

Examples/SimpleChatClient/SimpleChatClient.xcodeproj/project.pbxproj
Examples/SimpleGmailClient/SimpleGmailClient.xcodeproj/project.pbxproj
local-cli/generator-osx/templates/xcodeproj/project.pbxproj

Currently initial project of `v0.8.3` will thrown following errors:

Add missing `-lc++` flag for RN 0.26

---

React/Base/RCTRootView.m

Comparing to tracking rect, tracking area has two advantages:
* Tracking area could be updated automatically as view being resized.
* Tracking area does not need to make window as first responder to receive mouse move event.

Replace tracking rect with tracking area for mouse event tracking in RCTRootView

---

README.md

Just missing the closing code blocks tick marks.

Fixing Readme Syntax highlighting

---

Examples/UIExplorer/js/ButtonExample.js
Libraries/Components/Button/Button.macos.js
React/Views/RCTButtonManager.m

Adds [`state`][0] and [`allowsMixedState`][1] props to `Button` component.
This is my first PR for react-native-macos, so please let me know if I am missing something. :smile:
**Switch**:
```jsx
<Button type={'switch'} style={{width: 200}} title={'Single Checkbox'} state={0} />
<Button type={'switch'} style={{width: 200}} title={'Single Checkbox'} state={1} />
<Button type={'switch'} style={{width: 200}} title={'Single Checkbox'} allowsMixedState={true} state={-1} />
```
**Radio**:
```jsx
<Button type={'radio'} style={{width: 200}} title={'Single Radio'} state={0} />
<Button type={'radio'} style={{width: 200}} title={'Single Radio'} state={1} />
<Button type={'radio'} style={{width: 200}} title={'Single Radio'} allowsMixedState={true} state={-1} />
```
[0]: …

Add Button state and allowsMixedState props

---

local-cli/bundle/buildBundle.js

Fixes #106.
This was actually fixed in the main React Native repo with the same commit about 2 weeks ago (https://github.com/facebook/react-native/commit/a5678983bb16ff48f91ed43caafba96ca322f7dc). It would be really useful if @ptmt could document the process for bringing in change from the forked repository so others can help keep it up to date 👍

Fix not being able to archive

---

Libraries/Text/RCTTextFieldManager.m

The name of the property was incorrect.

Fix text alignment crash in RCTTextField

---

Examples/UIExplorer/js/UIExplorerList.macos.js
React/Base/RCTTouchHandler.m

I've added the `PanResponder` example back into the UIExamples project and then changed the `RCTTouchHander` to use the new `NSEvent` rather than looking up the one it previously had. This allows it to correctly update the location and timestamp.
I didn't know how the React ART was meant to look, so I've not fixed any problems there.
Fixes #109.

Fix pan responder by using the new native touch to set the react touch propterties

---

local-cli/commands.js
local-cli/runMacOS/findXcodeProject.js
local-cli/runMacOS/runMacOS.js

Allows us to run `react-native-macos run-macos` to build and run the app.
Borrowed heavily from `runIOS`

Create cli command to build and run macOS app.

---

React/Base/RCTTouchHandler.m

In RCTTouchHandler, touch states are removed in `-[RCTTouchHandler _recordRemovedTouches:]`, which is called in `-[RCTTouchHandler mouseUp:]`. The problem is `-[RCTTouchHandler mouseUp:]` is not guaranteed to be called, and when it's not, the touch states would be wrong.
So, correct me if I was wrong, I think touch states need to be cleared some where, and I think `-[NSGestureRecognizer reset]` might be the right place.

Clear touch handler states when gesture recognizer ended.

---

React/Modules/RCTAlertManager.m

Hi, i try to fix alerts callback and it's work now, but i don't understand some variables in RCTAlertManager.m:
```
NSMutableArray<NSAlert *> *_alerts;
NSMutableArray<RCTResponseSenderBlock> *_alertCallbacks;
NSMutableArray<NSArray<NSString *> *> *_alertButtonKeys;
```
So if you can explain for what it, i'll complete it =)
Thanks

Fix  #85 - callback associated with button in Alert.alert not working

---

packager/react-packager/src/node-haste/Package.js

This commit makes it possible to share code more broadly between react native platforms. For example, take the following package.json field:
package.json
```json
"react-native-macos": { "react-native": "react-native-macos" }
```
With this set our components can import from react-native rather than react-native-macos, allowing code sharing between react native platforms more easily.
Having the ability to use the same imports across platforms is incredibly important. Using the `browser` or `react-native` fields of package.json is the accepted way by the community to shim global requires (it's the only way that the React packager accepts shims). The React Native Web project uses a webpack alias to make it possible to use React Native code to target the web without modification.
The new …

Allow react-native-macos package.json shims

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/RCTTextField.h
Libraries/Text/RCTTextField.m
Libraries/Text/RCTTextFieldManager.m

This pull request adds support for `onSubmitEditing` on `<TextFields>`s.
The function `_renderIOS` was copied as `_renderMacOS` with the `onSubmitEditing` hook added, as iOS doesn't really have support for it and it didn't seem sensible to have them share that function any longer.
Looking forward to feedback.

Fix onSubmitEditing for text fields

---

Libraries/Text/RCTTextField.m
local-cli/index.js
local-cli/platform.js
local-cli/runMacOS/findXcodeProject.js
package-lock.json
package.json

Added RNPM plugin configuration.
Instead of running react-native-macos-cli you can now just run react-native-cli like:
```
react-native run-macos
````
This still needs adjustments .babelrc config and rn-cli-config to resolve the libraries correctly though.
If somebody know hows to solve this using the plugin please let me know :)

Merge 0.52.0 rnpm plugin

---

Libraries/ART/ARTSurfaceView.m

Core Graphics has a slightly different API on OSX

Merge 0.52.0 Update ART

---

Libraries/Components/ScrollResponder.js
Libraries/ReactNative/UIManager.js

Fix `scrollTo` in `ScrollView`. 
To support this change I had to populate the `Commands` property 
e.g. `UIManager.RCTNativeScrollView.Commands.scrollTo;` via this commit https://github.com/ptmt/react-native-macos/commit/3e2557061a0beff3bdf27d7f082f2676cfa132f2.

Fix scrollTo for ScrollView

---

Libraries/Components/ScrollResponder.js

I retested #208 with the latest (0.18.0) version, `Platform` must be imported, otherwise results in a crash when `scrollTo` is used.

Add missing import for #208

---

Libraries/Text/RCTTextField.m

TextInput placeholderText should still display even if no placeholderTextColor is set. This aligns with how NSTextField behaves.
```
<TextInput
placeholder="search"
/>
```

Fix placeholder not showing if placeholderTextColor is not set

---

Libraries/Text/RCTTextFieldManager.m

RCTTextInputManager.m seemed to be missing the property export for bezeled and bordered. This add that back.
```
RCT_EXPORT_VIEW_PROPERTY(bezeled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(bordered, BOOL)
```
TextInput can now configure whether the border/bezel is displayed.
```
<TextInput
bordered={false}
bezeled={false}
/>
```

Fix bordered and bezeled property not being forwarded

---

React/Modules/RCTRedBox.m

- add NSScrollView for scrolling the NSTableView
- fix clicking a stack frame to launch an editor
- center the RCTRedBoxWindow in the middle of the screen
- use a dark color theme (to save my eyeballs)
- make the buttons a little better looking
- change font family for stack frames
- clean up the code some
I would love to replace the 2nd stack trace (provided by `react-native`) with 1st one (provided by `react`), but I haven't looked into it yet.

fix: RCTRedBox tweaks

---

Libraries/BatchedBridge/MessageQueue.js
Libraries/BatchedBridge/NativeModules.js
React/Base/RCTLog.mm
React/CxxBridge/RCTCxxBridge.mm
React/Modules/RCTRedBox.m

- fix: RCTRedBox#copyStack
- use NSPasteboard correctly
- avoid truncating the error message too early
- avoid overwriting the first error with another error (regression from v0.18.3)
- trim whitespace in error message
- fix measurement of error message
&nbsp;
- fix: detect circular refs in bridge messages
- also, stringify invalid messages for easier debugging
&nbsp;
- fix: catch invalid native calls from JS
- This allows RCTRedBox to show when JS tries to send an invalid native call over the bridge. Without this commit, you need to check the Xcode logs to know what happened.
&nbsp;
- fix: re-enable redBox in _RCTLogNativeInternal
- This commented-out line was preventing RCTRedBox from appearing for certain errors (eg: failed to load bundle)
&nbsp;
- fix: "Failed to load bundle" error 
- …

More RCTRedBox improvements
